# config/meta.yml
meta_product_name: "SYNC"
meta_title: "SYNC - Where minds connect"
meta_description: "Do you think you know how your friend thinks better than they do about you? Try SYNC to find out"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
